#!/usr/bin/env python

import os
import whisper

os.makedirs("whisper-cache", exist_ok=True)


models = whisper.available_models()

for model in models:
    print(f"Downloading {model}...")
    whisper._download(whisper._MODELS[model], "whisper-cache")
